# Generated by Django 4.2.3 on 2023-07-30 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_follow_user1_follow_user2_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user2',
        ),
        migrations.AddField(
            model_name='follow',
            name='user_A',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_A', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='user_B',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_B', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
