# Generated by Django 4.2.3 on 2023-08-02 00:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_follow_user1_remove_follow_user2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user_A',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_B',
        ),
        migrations.AddField(
            model_name='follow',
            name='follow_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to='users.profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='time_followed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.profile'),
        ),
    ]
