# Generated by Django 4.2.3 on 2023-08-05 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0008_alter_tweet_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweets',
            field=models.ManyToManyField(blank=True, related_name='tweet_retweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
