# Generated by Django 4.2.3 on 2023-08-09 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_tweet_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_to', to='tweets.tweet'),
        ),
    ]
